SIZES=10 16 22 32 48 96 128

ICONS=feed.svg permalink.svg trackback.svg comment.svg share.svg edit.svg permalink2.svg permalink3.svg permalink4.svg clock.svg clock2.svg cancel.svg opml.svg download.svg upload.svg tag.svg

include ../include.mk

